/** Single token source. Apps extend this preset. No raw hex in components. */
module.exports = {
  theme: {
    extend: {
      colors: {
        bg: "var(--bg)",
        sidebar: "var(--sidebar)",
        topnav: "var(--topnav)",
        main: "var(--main)",
        card: "var(--card)",
        surface: "var(--surface)",
        "surface-secondary": "var(--surface-secondary)",
        "surface-hover": "var(--surface-hover)",
        "nav-active": "var(--nav-active)",
        "nav-hover": "var(--nav-hover)",
        control: "var(--control)",
        "control-active": "var(--control-active)",
        segment: "var(--segment)",
        "segment-active": "var(--segment-active)",
        "ring-track": "var(--ring-track)",
        "mobile-nav": "var(--mobile-nav)",
        border: "var(--border)",
        "border-hover": "var(--border-hover)",
        "border-subtle": "var(--border-subtle)",
        "border-faint": "var(--border-faint)",
        "border-control": "var(--border-control)",
        "border-segment": "var(--border-segment)",
        "border-secondary": "var(--border-secondary)",
        text: "var(--text)",
        "text-secondary": "var(--text-secondary)",
        "text-muted": "var(--text-muted)",
        muted: "var(--muted)",
        "text-disabled": "var(--text-disabled)",
        "text-axis": "var(--text-axis)",
        "text-hover": "var(--text-hover)",
        accent: "var(--accent)",
        "accent-hover": "var(--accent-hover)",
        "accent-fg": "var(--accent-fg)",
        danger: "var(--danger)",
        warning: "var(--warning)",
        info: "var(--info)",
      },
      borderRadius: {
        sm: "var(--radius-sm)",
        md: "var(--radius-md)",
        lg: "var(--radius-lg)",
        "mobile-nav": "var(--radius-mobile-nav)",
      },
      fontFamily: {
        // Apps must define --font-sans (web: IBM Plex; admin: aliased from Geist).
        sans: ["var(--font-sans)", "system-ui", "sans-serif"],
        mono: ["var(--font-mono)", "ui-monospace", "monospace"],
      },
      transitionDuration: {
        DEFAULT: "150ms",
      },
    },
  },
};
